---
title: "Untitled"
format: html
editor: visual
---

## Introduction

Over 800 women each day worldwide may away from pregnancy- and childbirth-related problems, and 5.3 million children worldwide are predicted to be under the age of five every year, with half of these deaths taking place in sub-Saharan Africa. The rates of maternal mortality, particularly in lower-income countries continue to be extremely high. The majority of these deaths occur in developing nations, primarily in sub-Saharan Africa and Southern Asia; sub-Saharan Africa alone accounts for two-thirds of these deaths. Nigeria, a nation in sub-Saharan Africa, continues to make a sizable contribution to these fatalities and is to blame for around 20% of all maternal fatalities worldwide. A Nigerian woman's lifetime risk of dying during pregnancy or childbirth is 1 in 18, which is higher than the sub-Saharan African average of 1 in 22 and the global average of 1 in 92. Women from developing nations generally have many more pregnancies than women from developed countries, despite this danger. In the context of the health-for-All Policy, family planning was recognized in the Alma-Ata Declaration (1978) as a crucial element of primary health care (PHC). Reproductive Health: A Strategy for the African Region (AFR/RC47/8), adopted by the WHO Regional Committee for Africa in 1997, supported family planning's critical role in achieving the best possible reproductive health status and overall wellbeing. Family planning is listed as an intervention for enhancing the quality of life of women in Women's Health: A Strategy for the African Region (AFR/RC53/11), which was accepted by the Regional Committee in 2003. Health ministers emphasized that early, repeated, and numerous pregnancies have a negative impact on women's nutritional state and increase their vulnerability to illnesses, physical weariness, and early aging. They emphasized the need to address family planning and particularly birth-spacing in order to improve quality of life of African women. The HIV/AIDS pandemic has made the effective implementation of family planning services and reproductive health programs in sub-Saharan Africa a tough commitment. Increased financial, human, and managerial resources are available for family planning initiatives as a result of the necessity to respond to the deteriorating HIV/AIDS situation.\[Ref\] Despite the evident need for access to sexual and reproductive health commodities (SRHC) in Kenya, Tanzania, Uganda, and Zambia, access has not been fully realized, with shortages, unaffordability, regulatory provisions, and supply chain concerns persisting\[Ref\]. Previous research in these countries has concentrated on identifying the supply and demand side hurdles to access, but extensive study on the accessibility and cost of these drugs at the health system level is absent. In Uganda, earlier study on the availability of SRH drugs revealed that access remains inadequate. However, extensive research on the availability and affordability of these medicines at the health system level is insufficient. \[5,6,7\] A prominent family planning initiative is the UNFPA Supplies partnership. It supports nearly 20 million women and girls worldwide each year, with 8.5 million in East and Southern Africa. It collaborates with companies, foundations, NGOs, civil society organizations, and governments to bring modern contraception and life-saving maternal health drugs to 50 of the world's poorest countries. 15 of these are located in East and Southern Africa. \[Ref\] Family planning (FP) is a human right, and preserving women's FP access is critical to protecting the health and well-being of mothers and children. Article 35(9) of the Federal Democratic Republic of Ethiopia's Constitution clearly states a woman's right to FP, stating that "to prevent harm arising from pregnancy and childbirth and to safeguard their health, women have the right to access to family planning education, information, and capacity." The Ethiopian government's decision in 2007 to abolish the contraceptive tax and allow the Ethiopian Pharmaceutical Supply Agency to procure and distribute contraceptives facilitated contraceptive supply and access. At the same time, the government extended the resource base by enhancing domestic financial resources given to the FP program: the annual allocation to the FP budget has increased over the last decade. However, the country's FP program is still heavily reliant on external funding. Advocates must continue to press for increased government budgetary allocations to FP and reproductive health programs. \[Ref\]

# Supply chain of family planning commodities {#sec-lit}

\*Efficient public health supply chain performance is critical for ensuring access to health supplies and, consequently, excellent health outcomes. This is especially essential in most Sub-Saharan African nations where the public and mission health sectors serve a large proportion of the population.\[10\] All public health facilities in Ethiopia acquire essential drugs primarily through the integrated pharmaceuticals logistics system (IPLS), a centralized reporting and distribution system overseen by the drugs Fund and Supply Agency (PFSA). PFSA is in charge of acquiring, storing, and distributing health commodities for both public and commercial health facilities. IPLS must fulfill the Six Rights to ensure that patients always obtain pharmaceuticals (the appropriate drugs, in the right quality, in the right quantity, at the right place, at the right time, and for the right price). Among the medications managed by the IPLS are maternal and child health products.\[11\] A UN Commission report in 2012 defined the 13 life-saving commodities, as medicines, medical devices, and health supplies that effectively address avoidable causes of death during pregnancy and childbirth that, if more widely accessed and properly used, could significantly reduce preventable deaths among women.\[12\]

UNCoLSC emphasized the following challenges and limitations to in-country SCM: - • Lack of capacity in SCM activities • Limited number of staff in SCM activities • Little use of procurement flexibilities (e.g., framework contracts) • Inadequate storage space and conditions • Poor inventory management • Budgetary constraints, particularly for key commodities and SCM • Poor LMIS • Few health staff trained in the particular of SCM • staff turnover and mobility • Lack of supportive supervision • Lack of national policy guidelines on the use of certain products This study will cover the supply chain management of family planning commodities specifically the forecasting step in the supply chain as well as the forecasting accuracy.

## Why forecasting?

In general, a pharmaceutical forecast must consider both a disease and a healthcare system, and the key to successfully executing this is making good use of the data at hand to accurately reflect this complexity. Forecasting plays a major role in many circumstances, and it is seen as a crucial assistance to successful and efficient planning regardless of the conditions or time horizons involved. The predictability of an event is determined by how well we understand the components that contribute to it, the amount of data available, and if projections can influence what we are attempting to anticipate. Forecasts may be very accurate when these three requirements are met. A time series is anything that is seen sequentially across time and attempts to predict how the sequence of observations will continue in the future. Forecasting time series typically estimate seasonal trends and patterns, and by evaluating the data, any additional details such as marketing endeavors, rival activity, and changing economic situations may be detected. \[14\] Forecasting is the process of predicting the future as accurately as possible with all available information, including previous information as well as an understanding of any future occurrences that may affect the prediction. A number of forecasting approaches have been developed, with conventional models (TM) and Explanatory Models (EM) emerging as the most useful. \[15\] The first, which is based on statistical methodologies, is used under the assumption that prior demand can be quantitatively estimated to predict future demand. This means they examine historical data trends and attempt to forecast the future based on these underlying patterns. The second one, on the other hand, presume that the variable being anticipated is connected to other factors in the environment and does not depend only on its own prior values. Methods in this group typically contain additional internal and exogenous factors, providing for a more complete description of actuality.\[16\] Methods of forecasting include dartboard methods also known as gut feel, workstation methods, simple spreadsheet methods, analytic spreadsheet methods, systems dynamics methods, alignment with lifecycles and qualitative & quantitative methods. In which, each of these methods have their own advantages and disadvantages as well. The resource question is one of the factors to consider when choosing a forecasting approach, which forecasters commonly refer to as the 'chicken and egg' question. In new product forecasting, the question is put forth, 'Do I generate a forecast for the product assuming a "optimal" level of marketing and sales resources are deployed, or do I develop a prediction using a given level of marketing and sales resources, which may be sub-optimal?' The dilemma occurs because the decision of resource levels used to a product is tied to the product's anticipated potential which is also a function of the level of resources applied to the product.\[17\]
